### ISSUE TITLE
Question: Is there a particular reason why Synth attributes are initialized with __setattr__

### ISSUE THREAD

**Issue by aleneum** [interactive-sonification/mesonic#6]
While `Parameter` initializes attributes via direct assignments like `self._synth = synth`, `Synth` uses a rather verbose ` object.__setattr__(self, "_context", context)`. Is there a particular benefit of doing it that way? I'd consider `setattr(self, "_context", context)` or `self._context = context` more readable.

**Comment by dreinsch** [comment]
Yes, the reason for this is that the `Synth` class overrides `__setattr__` and using `object.__setattr__(...)` avoids using it in `__init__` as both `setattr(self, "_context", context)` or `self._context = context` would be using the overwritten function.

The reason to avoid using the overwritten `__setattr__` is that it restricts the Synth object to only set attributes that are already existing or the parameters stored in the `_params` dict using `Synth.paramter_name = parameter_value` for syntactic sugar. This also avoids the user setting a parameter using a misspelled name like f.e. `Synth.freg = 440` .

However this implementation can't be used in `__init__` because in `__init__` the attributes do not exist already and the usage of `setattr` or `self.name = value` would lead to an `AttributeError` in the custom  `__setattr__`.

Here is a minimal example class demonstrating the issue.

    class Example:
    
        def __init__(self, params):
            self._params = params
            # object.__setattr__(self, "_params", params)
          
        def __setattr__(self, name, value):
            try:
                object.__getattribute__(self, name)
            except AttributeError:
                if name not in self._params:
                    raise
                else:
                    self._params[name] = value
            else:
                object.__setattr__(self, name, value)

If `object.__setattr__(...)` is changed with `setattr` or `self._x = x`  it will lead to an `AttributeError` when a object is created using `Example({"test": 1})` which is raised by `object.__getattribute__(self, name)` as well as another `AttributeError` in the handling of this `AttributeError` as `self._params` cannot be found.

Using `object.__setattr__(self, "_params", params)` allows creating objects.

I suggest the following improvements:

- [ ]  Perhaps a short comment about this and a link to this issue should be added to `Synth.__init__`.

- [ ] Also `__setattr__` should clearly state that the Synth class does not allow adding new attributes instead of simply reraising the `AttributeError`
 
- [ ] I also noticed that the parameter setting line in the `Synth.__setattr__` implementation is on the last line but should be inside of the except like it in the `Example` class.

**Comment by aleneum** [comment]
ah okay, I didn't dive deep enough to catch the `__setattr__` override. `object.__setattr__` is a clever way of avoiding custom property handling in the override. If `Synth` could be a future target for Subclass/Mixin usage `super().__setattr__` could add a little more flexibility just in case. I agree that a short comment would be nice and more accurate error messages is also always a win.
